FROM mcr.microsoft.com/devcontainers/python:3.9

USER vscode

ENV PIPX_HOME=/usr/local/py-utils
RUN python3 -m pip install pip --upgrade \
    && python3 -m pip install pipx wheel --upgrade
COPY .devcontainer/pipx-install.sh pipx-install.sh
RUN ./pipx-install.sh

USER root

ENV PIP_TARGET=/usr/local/pip-global
ENV PYTHONPATH=${PIP_TARGET}:${PYTHONPATH}
ENV PATH=${PIP_TARGET}/bin:${PATH}
RUN if ! cat /etc/group | grep -e "^pip-global:" > /dev/null 2>&1; then groupadd -r pip-global; fi \
    && usermod -a -G pip-global vscode \
    && umask 0002 && mkdir -p ${PIP_TARGET} \
    && chown :pip-global ${PIP_TARGET} \
    && ( [ ! -f "/etc/profile.d/00-restore-env.sh" ] || sed -i -e "s/export PATH=/export PATH=\/usr\/local\/pip-global:/" /etc/profile.d/00-restore-env.sh )
