"""Enum for Feather.js icons."""
from enum import Enum

Icon = Enum(
    'Icon',
    (
        (name.replace('-', '_').upper(), name)
        for name in [
            'activity',
            'alert-triangle',
            'archive',
            'bar-chart',
            'battery',
            'battery-charging',
            'bell',
            'bluetooth',
            'book',
            'book-open',
            'calendar',
            'clipboard',
            'cloud',
            'codepen',
            'compass',
            'dollar-sign',
            'file-text',
            'git-commit',
            'grid',
            'heart',
            'image',
            'info',
            'key',
            'lock',
            'mail',
            'map',
            'map-pin',
            'maximize',
            'message-square',
            'mic',
            'monitor',
            'package',
            'paperclip',
            'pause',
            'phone',
            'play-circle',
            'power',
            'save',
            'settings',
            'share-2',
            'terminal',
            'type',
            'user',
            'wifi',
            'zap',
        ]
    ),
)
